Update patch set 11
Patch Set 11:

Is this supposed to be all that was needed for MSVS 2017 support? I get the error below when trying to use it on a system that’s only seen VS2017.

vcvarsall.bat has moved, and it’s now in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat. It doesn’t appear that GYP has been updated to look for it at this path.

Traceback (most recent call last):
  File "C:\chrome\crashpad\crashpad\build\gyp_crashpad.py", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\chrome\crashpad\crashpad\build\gyp_crashpad.py", line 73, in main
    result = gyp.main(args)
  File "C:\chrome\crashpad\crashpad\third_party\gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\chrome\crashpad\crashpad\third_party\gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\chrome\crashpad\crashpad\third_party\gyp\gyp\pylib\gyp\generator\ninja.py", line 2483, in GenerateOutput
    config_name)
  File "C:\chrome\crashpad\crashpad\third_party\gyp\gyp\pylib\gyp\generator\ninja.py", line 1965, in GenerateOutputForConfig
    toplevel_build, generator_flags, shared_system_includes, OpenOutput)
  File "C:\chrome\crashpad\crashpad\third_party\gyp\gyp\pylib\gyp\msvs_emulation.py", line 1032, in GenerateEnvironmentFiles
    args = vs.SetupScript(arch)
  File "C:\chrome\crashpad\crashpad\third_party\gyp\gyp\pylib\gyp\MSVSVersion.py", line 119, in SetupScript
    script_path)
Exception: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\vcvarsall.bat is missing - make sure VC++ tools are installed.

Patch-set: 11
CC: Gerrit User 1174099 <1174099@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>